# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ""
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, "README.rst")
if os.path.exists(readme_path):
    with open(readme_path, "rb") as stream:
        readme = stream.read().decode("utf8")


setup(
    long_description=readme,
    name="chitanda",
    version="0.0.5",
    description="An extensible Discord & IRC bot.",
    python_requires="==3.*,>=3.7.0",
    project_urls={"repository": "https://github.com/azuline/chitanda"},
    author="azuline",
    author_email="azuline@riseup.net",
    license="GPL-3.0",
    entry_points={"console_scripts": ["chitanda = chitanda.__main__:run"]},
    packages=[
        "chitanda",
        "chitanda.listeners",
        "chitanda.modules",
        "chitanda.modules.irc_channels",
        "chitanda.modules.lastfm",
        "chitanda.modules.quotes",
        "chitanda.modules.tell",
    ],
    package_dir={"": "."},
    package_data={
        "chitanda.modules.irc_channels": ["migrations/*.sql"],
        "chitanda.modules.lastfm": ["migrations/*.sql"],
        "chitanda.modules.quotes": ["migrations/*.sql"],
        "chitanda.modules.tell": ["migrations/*.sql"],
    },
    install_requires=[
        "aiohttp==3.*,>=3.5.0",
        "appdirs==1.*,>=1.4.0",
        "click==7.*,>=7.0.0",
        "discord.py==1.*,>=1.2.0",
        "pydle==0.*,>=0.9.1",
        "requests==2.*,>=2.22.0",
    ],
    extras_require={
        "dev": [
            "black==20.*,>=20.8.0.b1",
            "flake8==3.*,>=3.7.0",
            "isort==5.*,>=5.6.4",
            "pytest==5.*,>=5.0.0",
            "pytest-asyncio==0.*,>=0.14.0",
            "pytest-cov==2.*,>=2.7.0",
            "sphinx==3.*,>=3.3.0",
            "sphinx-rtd-theme==0.*,>=0.4.3",
        ]
    },
)
